default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: maze_development
  host: localhost

test:
  <<: *default
  database: maze_test
  host: localhost

production:
  <<: *default
  database: maze_production
